name: README doctests

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: udpate
      run: |
        sudo apt-get update
    - name: Install curl
      run: |
        sudo apt-get install curl
    - name: Install rust
      run: |
        curl --proto '=https' --tlsv1.2 -sSf -y https://sh.rustup.rs | sh
        sudo apt-get install rustc cargo
    - name: Install pip for Python-3
      run: |
        sudo apt-get install python3-pip python3-dev
    - name: Install Python libraries
      run: |
        python3 -m pip install numpy shapely scipy matplotlib toml
    - name: Install HDF5 Libraries
      run: |
        sudo apt install libhdf5-dev
    - name: test Python Bindings
      run: |
        python3 -m pip install setuptools_rust testresources setuptools wheel
        python3 -m pip install --upgrade pip setuptools wheel
        python3 -m pip install .
    - name: run byexample
      run: |
        byexample -l python3 -vvv
